version: '3'

env:
  TITLE: devops-final-task
  TAG:
    sh: date "+%y-%m-%d-%H.%M"

tasks:
  build:
    cmds:
      - sudo docker build -t {{.TITLE}}:{{.TAG}} .
      - echo Success build. name={{.TITLE}}:{{.TAG}}

  test:
    cmds:
      - sudo docker run {{.TITLE}}:{{.TAG}} test

  run-dev-server:
    cmds:
      - sudo docker run {{.TITLE}}:{{.TAG}} runserver

  run-prod-server:
    cmds:
      - sudo docker run -p 8000:8000 {{.TITLE}}:{{.TAG}} gunicorn

  run-compose-prod:
    cmds:
      - sudo docker compose up prod

  run-compose-migrate:
    cmds:
      - sudo docker compose run migrate 

  down:
    cmds:
      - sudo docker compose down
