apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: alin-final-task

images:
  - name: final-task
    newName: S4B1K24/alin-final-task
    newTag: v1.1.0

resources:
- deployment.postgres.yaml
- service.postgres.yaml
